name: Post welcome comment

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"